description = "Clears and removes all workflow-generated files."
prompt = """
You have been asked to clear the workspace of all workflow-generated files.

## Clear Workflow Files

Your goal is to find and remove all of the following files: `RESEARCH.md`, `PLAN.md`, `TODO.md`, `ACT.md`, `TEST.md`.

## Execution Rules
1.  **Find Files:** Use your tools to search for all instances of the workflow files. They may be in the root directory or in subdirectories (e.g., `tasks/`).
2.  **List and Confirm:** Before deleting anything, you **must** list all the files you have found and ask the user for explicit confirmation to delete them. This is a destructive action.
3.  **Delete:** Once the user confirms, use your tools to delete the identified files.
4.  **Report:** Inform the user that the files have been cleared.

If no files are found, simply inform the user of that.
"""
